obj-$(CONFIG_SND_SOC_DBMD2P3_UART) += dbmd2-uart.o
obj-$(CONFIG_SND_SOC_DBMD2P3_SPI) += dbmd2-spi.o
obj-$(CONFIG_SND_SOC_DBMD2P3_I2C) += dbmd2-i2c.o
obj-$(CONFIG_SND_SOC_DBMD2P3) += dbmd2.o dbmd2-cdev.o dbmd2-customer.o dbmd2-i2s.o
